spring:
  application:
  name: petwalk

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petwalk?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    #password : aaaaaaaa
    #password: 1234
    password : aaaaaaaa

  jpa:
    open-in-view: false #html??? jpa? ???? ???? ???.
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# naver section info end by david------------------

naver:
  uri:
    auth: https://nid.naver.com/oauth2.0
    api: https://openapi.naver.com

  redirect-url: http://localhost:8080/oauth/naver
  id: RjDcYhXTVT0js2LE54Yh
  secret: faZkrvWzzm
  authorization-grant-type: authorization_code
  scope: name,email,profile_image,mobile
  client-name: Naver
  provider:
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: responsed

kakao:
  uri:
    auth: https://kauth.kakao.com
    token: https://kauth.kakao.com/oauth/token
    api: c68134e375eb0d293c1d210e71ff8a69

  redirect-url: http://localhost:8080/oauth/kakao
  client-id: 5edb768591f2df4dfdde8e09e1762f62
  client-secret: 4IVEbVc7hfxhf9GtSE1ZU4JoVMBovMH0
  authorization-grant-type: authorization_code
  scope: profile_nickname,account_email # 요청할 스코프를 여기에 추가
  client-name: Kakao
  provider:
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me
      user-name-attribute: responsed