spring:
  application:
  name : PetWalk

  datasource:
    url : jdbc:mysql://127.0.0.1:3306/petwalk?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username : root
    password : 1234

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
